### PR TITLE
Create drag and drop

### PR DESCRIPTION
**Pull request by GreenyNg**

### CODE REVIEW

**Comment by GreenyNg** [comment]
I apologise for the delay in create this pull request. I came up with the design but had a hard time getting a developer to commit to completing the drag and drop. Kindly review this and propose any changes or requests you might have. Thank you

**Comment by marshalmiller** [comment]
@GreenyNg No worries. Thank you for taking the time to help with our project. I will begin reviewing the changes and get back to you with any feedback.

**Comment by marshalmiller** [comment]
@GreenyNg Sorry for the delay. I see the Figma file. Were you just submitting the design, or did you have some code to implement that design? Either contribution is appreciated, I just want to make sure. Thanks.

**Comment by GreenyNg** [comment]
Hello, it's alright. I'm glad to hear from you.

In response to your question, it's just the design. I had tried to get
someone to work with me on implementing the design but that wasn't
forthcoming.

I would like to know if the design sits well with you or if you would like
me to make any adjustments whatsoever. I can then go ahead and design a
responsive version of the drag n drop.

**Comment by marshalmiller** [comment]
@GreenyNg I think it's a great design. I say go for it.

**Comment by GreenyNg** [comment]
Alright, thank you!

**Pull request closed without merging**
