### PR TITLE
CAPTCHA and pdf report

### LINKED ISSUE #159: Add Captcha to Submission
As this site expands, it would probably be a good idea to add a Captcha to the service. Here is the documentation to use reCaptcha.

https://developers.google.com/recaptcha/docs/display

### PR DESCRIPTION
**Pull request by aditirao7**
Resolves #159 

In order to get it working on the server you need to make a [reCAPTCHA](https://www.google.com/recaptcha/admin/enterprise) key. Then add the environment variables CAPTCHA_KEY_ID and CAPTCHA_SECRET_KEY on heroku. Also please make a separate key for development purposes so that we can update the documentation for local setup.

Screenshot from 2023-10-15 19-13-22

### CODE REVIEW

**Comment by marshalmiller** [comment]
@aditirao7 This is amazing! I do have one more request. Could we create an environment variable that is just true or false and asks if the person wants to run the captcha? This way we could use the captcha on production, but when people are testing at home, they don't get stuck on the captcha stuff. Is that possible? I really appreciate your work on this.

**Comment by aditirao7** [comment]
@marshalmiller Oh yeah good idea, I'll do a follow up PR if you don't mind? My commit history is a little messy

**Comment by marshalmiller** [comment]
@aditirao7 Feel free to submit it any way you'd like. Thank you so much.

**Comment by marshalmiller** [comment]
Merged!

**Pull request merged**
